[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Testing
fuzz_runs = 256
verbosity = 2

# Formatter
line_length = 100
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
local = "http://localhost:8545"
node1 = "http://localhost:8545"
node2 = "http://localhost:8546"
node3 = "http://localhost:8547"
